
import javax.swing.JOptionPane;

public class DashboardFrame extends javax.swing.JFrame {

   private Usuario login;
   private String nombreTitulo, apellidoTitulo, rolTitulo;
   
   /**
    * Creates new form DashboardFrame
    */
   public DashboardFrame(Usuario login){
      
      initComponents();
      
      this.login = login;
      
      nombreTitulo = login.getNombre().substring(0, 1).toUpperCase() +
         login.getNombre().substring(1).toLowerCase();
      apellidoTitulo = login.getApellido().substring(0, 1).toUpperCase() +
         login.getApellido().substring(1).toLowerCase();
      rolTitulo = login.getRol().substring(0, 1).toUpperCase() +
         login.getRol().substring(1).toLowerCase();
      
      etiquetaTituloDashboard.setText("<html>" + rolTitulo + ": " + nombreTitulo + " " +
         apellidoTitulo + ".</html>");
      
      campoNombreCuenta.setText(login.getNombre());
      campoApellidoCuenta.setText(login.getApellido());
      campoRolCuenta.setText(login.getRol());
      campoUsuarioCuenta.setText(login.getUsuario());
   }
   
   public void restaurar(){
      campoNombreCuenta.setText(login.getNombre());
      campoApellidoCuenta.setText(login.getApellido());
      campoRolCuenta.setText(login.getRol());
      campoUsuarioCuenta.setText(login.getUsuario());
   }
   
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      etiquetaTituloDashboard = new javax.swing.JLabel();
      jTabbedPane1 = new javax.swing.JTabbedPane();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      campoNombreCuenta = new javax.swing.JTextField();
      campoApellidoCuenta = new javax.swing.JTextField();
      campoRolCuenta = new javax.swing.JTextField();
      campoUsuarioCuenta = new javax.swing.JTextField();
      botonGuardarCuenta = new javax.swing.JButton();
      botonCambiarContrasenaCuenta = new javax.swing.JButton();
      botonRestaurarCuenta = new javax.swing.JButton();
      botonLimpiarCuenta = new javax.swing.JButton();
      jPanel3 = new javax.swing.JPanel();
      jPanel4 = new javax.swing.JPanel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      etiquetaTituloDashboard.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
      etiquetaTituloDashboard.setForeground(new java.awt.Color(0, 0, 0));
      etiquetaTituloDashboard.setText("jLabel1");

      jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(0, 0, 0));
      jLabel1.setText("<html>Datos de usuario.</html>");

      jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(0, 0, 0));
      jLabel2.setText("Nombre:");

      jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(0, 0, 0));
      jLabel3.setText("Apellido:");

      jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(0, 0, 0));
      jLabel4.setText("Rol:");

      jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(0, 0, 0));
      jLabel5.setText("Nombre de usuario:");

      campoNombreCuenta.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
      campoNombreCuenta.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            campoNombreCuentaActionPerformed(evt);
         }
      });

      campoApellidoCuenta.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

      campoRolCuenta.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

      campoUsuarioCuenta.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

      botonGuardarCuenta.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
      botonGuardarCuenta.setForeground(new java.awt.Color(0, 0, 0));
      botonGuardarCuenta.setText("Guardar");
      botonGuardarCuenta.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonGuardarCuentaActionPerformed(evt);
         }
      });

      botonCambiarContrasenaCuenta.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
      botonCambiarContrasenaCuenta.setForeground(new java.awt.Color(0, 0, 0));
      botonCambiarContrasenaCuenta.setText("Cambiar contraseña");
      botonCambiarContrasenaCuenta.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonCambiarContrasenaCuentaActionPerformed(evt);
         }
      });

      botonRestaurarCuenta.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
      botonRestaurarCuenta.setForeground(new java.awt.Color(0, 0, 0));
      botonRestaurarCuenta.setText("Restaurar");
      botonRestaurarCuenta.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonRestaurarCuentaActionPerformed(evt);
         }
      });

      botonLimpiarCuenta.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
      botonLimpiarCuenta.setForeground(new java.awt.Color(0, 0, 0));
      botonLimpiarCuenta.setText("Limpiar campos");
      botonLimpiarCuenta.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonLimpiarCuentaActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(69, 69, 69)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel2)
                     .addComponent(jLabel4)
                     .addComponent(jLabel3)
                     .addComponent(jLabel5))
                  .addGap(18, 18, 18)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(campoNombreCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                     .addComponent(campoApellidoCuenta)
                     .addComponent(campoRolCuenta)
                     .addComponent(campoUsuarioCuenta)))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(botonGuardarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(botonCambiarContrasenaCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(botonRestaurarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(botonLimpiarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addContainerGap(80, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(229, 229, 229))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(40, 40, 40)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(campoNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(campoApellidoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(campoRolCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(campoUsuarioCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(39, 39, 39)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(botonGuardarCuenta)
               .addComponent(botonCambiarContrasenaCuenta))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(botonLimpiarCuenta)
               .addComponent(botonRestaurarCuenta))
            .addContainerGap(58, Short.MAX_VALUE))
      );

      jTabbedPane1.addTab("Cuenta", jPanel2);

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 600, Short.MAX_VALUE)
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 439, Short.MAX_VALUE)
      );

      jTabbedPane1.addTab("Inventario", jPanel3);

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 600, Short.MAX_VALUE)
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 439, Short.MAX_VALUE)
      );

      jTabbedPane1.addTab("Clientes", jPanel4);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(etiquetaTituloDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
         .addComponent(jTabbedPane1)
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(etiquetaTituloDashboard)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTabbedPane1))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void campoNombreCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreCuentaActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_campoNombreCuentaActionPerformed

   private void botonGuardarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarCuentaActionPerformed
      
      String nombre = campoNombreCuenta.getText();
      String apellido = campoApellidoCuenta.getText();
      String rol = campoRolCuenta.getText();
      String usuario = campoUsuarioCuenta.getText();
      
      if(nombre.compareTo("") == 0 || apellido.compareTo("") == 0
         || rol.compareTo("") == 0 || usuario.compareTo("") == 0){
         JOptionPane.showMessageDialog(
            null,
            "<html><strong>Ninguno de los campos debe estar vacio!<strong><html>",
            null,
            JOptionPane.ERROR_MESSAGE
         );
      }else{
         if(nombre.compareTo(login.getNombre()) == 0 && apellido.compareTo(login.getApellido()) == 0
            && rol.compareTo(login.getRol()) == 0 && usuario.compareTo(login.getUsuario()) == 0){
            JOptionPane.showMessageDialog(
               null,
               "<html><strong>No se han realizado cambios en sus datos de usuario!<strong><html>",
               null,
               JOptionPane.WARNING_MESSAGE
            );
         }else{
            Conexion conexion = new Conexion();
            if(nombre.compareTo(login.getNombre()) != 0){
               conexion.actualizarDatoUsuario(login.getId(), "nombre", nombre);
               String antiguoNombre = nombreTitulo;
               nombreTitulo = nombre.substring(0, 1).toUpperCase() + nombre.substring(1).toLowerCase();
               etiquetaTituloDashboard.setText(
                  etiquetaTituloDashboard.getText().replace(antiguoNombre, nombreTitulo)
               );
            }
            if(apellido.compareTo(login.getApellido()) != 0){
               conexion.actualizarDatoUsuario(login.getId(), "apellido", apellido);
               String antiguoApellido = apellidoTitulo;
               apellidoTitulo = apellido.substring(0, 1).toUpperCase() + apellido.substring(1).toLowerCase();
               etiquetaTituloDashboard.setText(
                  etiquetaTituloDashboard.getText().replace(antiguoApellido, apellidoTitulo)
               );
            }
            if(rol.compareTo(login.getRol()) != 0){
               conexion.actualizarDatoUsuario(login.getId(), "rol", rol);
               String antiguoRol = rolTitulo;
               rolTitulo = rol.substring(0, 1).toUpperCase() + rol.substring(1).toLowerCase();
               etiquetaTituloDashboard.setText(
                  etiquetaTituloDashboard.getText().replace(antiguoRol, rolTitulo)
               );
            }
            if(usuario.compareTo(login.getUsuario()) != 0){
               conexion.actualizarDatoUsuario(login.getId(), "usuario", usuario);
            }
            conexion.cerrarConexion();
            JOptionPane.showMessageDialog(
               null,
               "<html><strong>Sus datos fueron actualizados satisfactoriamente!<strong><html>",
               null,
               JOptionPane.INFORMATION_MESSAGE
            );
         }
      }
      
   }//GEN-LAST:event_botonGuardarCuentaActionPerformed

   private void botonRestaurarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaurarCuentaActionPerformed
      
      restaurar();
      
   }//GEN-LAST:event_botonRestaurarCuentaActionPerformed

   private void botonLimpiarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarCuentaActionPerformed
      
      campoNombreCuenta.setText("");
      campoApellidoCuenta.setText("");
      campoRolCuenta.setText("");
      campoUsuarioCuenta.setText("");
      
   }//GEN-LAST:event_botonLimpiarCuentaActionPerformed

   private void botonCambiarContrasenaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarContrasenaCuentaActionPerformed
      
      
      
   }//GEN-LAST:event_botonCambiarContrasenaCuentaActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            //new DashboardFrame().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton botonCambiarContrasenaCuenta;
   private javax.swing.JButton botonGuardarCuenta;
   private javax.swing.JButton botonLimpiarCuenta;
   private javax.swing.JButton botonRestaurarCuenta;
   private javax.swing.JTextField campoApellidoCuenta;
   private javax.swing.JTextField campoNombreCuenta;
   private javax.swing.JTextField campoRolCuenta;
   private javax.swing.JTextField campoUsuarioCuenta;
   private javax.swing.JLabel etiquetaTituloDashboard;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JTabbedPane jTabbedPane1;
   // End of variables declaration//GEN-END:variables
}
